export const RECIPE_TYPES = [
  { label: "🍕 Pizza", value: "Pizza" },
  { label: "🍔 Hamburger", value: "Hamburger" },
  { label: "🍜 Asiatic", value: "Asiatic" },
  { label: "🌯 Burrito", value: "Burrito" },
  { label: "🍜 Noodles", value: "Noodles" },
  { label: "🍝 Pasta", value: "Pasta" },
  { label: "🦞 Sea food", value: "Sea food" },
  { label: "🍖 Barbecue", value: "Barbecue" },
  { label: "🐟 Fish", value: "Fish" },
  { label: "🥗 Salad", value: "Salad" },
  { label: "🥟 Appetizer", value: "Appetizer" },
  { label: "🍢 Kebab", value: "Kebab" },
  { label: "🍣 Sushi", value: "Sushi" },
  { label: "🥞 Brunch", value: "Brunch" },
  { label: "🥪 Sandwich", value: "Sandwich" },
  { label: "☕ Coffee", value: "Coffee" },
  { label: "🌮 Taco", value: "Taco" },
  { label: "🥦 Vegetarian", value: "Vegetarian" },
  { label: "🌱 Vegan", value: "Vegan" },
  { label: "🍽️ Other", value: "Other" },
];
