// export type RecipeType =
//   | "Pizza"
//   | "Hamburger"
//   | "Asiatic"
//   | "Burrito"
//   | "Noodles"
//   | "Pasta"
//   | "Sea food"
//   | "Barbecue"
//   | "Fish"
//   | "Salad"
//   | "Appetizer"
//   | "Kebab"
//   | "Sushi"
//   | "Brunch"
//   | "Sandwich"
//   | "Coffee"
//   | "Taco"
//   | "Vegetarian"
//   | "Vegan"
//   | "Other"
//   | "";
